import type { TripRequest, TripResponse } from "@/types/trip";
import sampleTrip from "./sampleTrip.json";

/** Static offline demo generated by backend/generate_sample.py. No UI HOS math. */
export function buildMockTrip(_request: TripRequest): TripResponse {
  return structuredClone(sampleTrip) as unknown as TripResponse;
}

export const sampleTripRequest: TripRequest = {
  current_location: { name: "Dallas, TX", lat: 32.7767, lng: -96.797 },
  pickup_location: { name: "Houston, TX", lat: 29.7604, lng: -95.3698 },
  dropoff_location: { name: "Miami, FL", lat: 25.7617, lng: -80.1918 },
  current_cycle_used: 20,
};
